import { StyleSheet } from 'react-native';

import { FlipOn } from '@/constants/flipon';

export const sessionStyles = StyleSheet.create({
  hero: {
    backgroundColor: FlipOn.dark,
    borderRadius: 22,
    padding: 18,
    gap: 8,
  },
  kicker: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    color: FlipOn.accent,
  },
  title: { fontSize: 26, fontWeight: '800', color: '#fff', lineHeight: 32 },
  subtitle: { fontSize: 14, lineHeight: 20, color: '#C7CBD1' },
  card: {
    backgroundColor: FlipOn.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: FlipOn.line,
    padding: 16,
    gap: 10,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardTitle: { fontSize: 15, fontWeight: '700', color: FlipOn.ink },
  count: { fontSize: 13, fontWeight: '700', color: FlipOn.accentInk },
  groupLabel: { fontSize: 12, fontWeight: '600', color: FlipOn.muted, marginTop: 4 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    minHeight: 36,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: FlipOn.line,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.surface,
  },
  chipSelected: { borderColor: FlipOn.accent, backgroundColor: FlipOn.accentSoft },
  chipText: { fontSize: 13, fontWeight: '600', color: FlipOn.muted },
  chipTextSelected: { color: FlipOn.accentInk },
  line: { paddingVertical: 10, gap: 2 },
  lineBorder: { borderBottomWidth: 1, borderBottomColor: FlipOn.soft },
  lineLabel: { fontSize: 12, color: FlipOn.muted },
  lineValue: { fontSize: 15, fontWeight: '600', color: FlipOn.ink },
  qrBlock: { alignItems: 'center', gap: 10, paddingVertical: 6 },
  qrFrame: {
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: FlipOn.line,
    backgroundColor: FlipOn.surface,
  },
  qrHint: { fontSize: 13, fontWeight: '600', color: FlipOn.muted },
  hint: { fontSize: 12, lineHeight: 18, color: FlipOn.muted },
  waitBox: {
    borderRadius: 12,
    backgroundColor: FlipOn.soft,
    padding: 12,
    gap: 4,
  },
  waitTitle: { fontSize: 14, fontWeight: '700', color: FlipOn.ink },
  waitText: { fontSize: 13, lineHeight: 18, color: FlipOn.muted },
  readyBox: {
    borderRadius: 12,
    backgroundColor: FlipOn.successSoft,
    padding: 12,
  },
  readyText: { fontSize: 13, fontWeight: '700', color: FlipOn.success },
  secondaryButton: {
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: FlipOn.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: { fontSize: 14, fontWeight: '700', color: FlipOn.ink },
  primaryButton: {
    minHeight: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.accent,
  },
  primaryDisabled: { opacity: 0.45 },
  primaryButtonText: { fontSize: 16, fontWeight: '700', color: '#fff' },
});
