import { StyleSheet } from 'react-native';

import { FlipOn } from '@/constants/flipon';

export const homeStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: FlipOn.bg },
  flex: { flex: 1 },
  scroll: { flex: 1 },
  container: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 110,
    gap: 20,
  },
  top: { gap: 2 },
  hello: { fontSize: 14, fontWeight: '600', color: FlipOn.muted },
  title: { fontSize: 32, fontWeight: '800', color: FlipOn.ink, letterSpacing: -0.6 },
  subtitle: { marginTop: 6, fontSize: 15, lineHeight: 22, color: FlipOn.muted },
  pressed: { opacity: 0.88 },

  heroWrap: { gap: 10 },
  hero: { backgroundColor: FlipOn.dark, borderRadius: 24, padding: 18, gap: 10 },
  heroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  badgeLive: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: FlipOn.accent },
  badgeLiveText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  heroCode: { color: '#A8ADB5', fontSize: 13, fontWeight: '800', letterSpacing: 1.2 },
  heroTitle: { color: '#fff', fontSize: 22, fontWeight: '800', letterSpacing: -0.3 },
  heroText: { color: '#C7CBD1', fontSize: 14, lineHeight: 20 },
  progressBlock: { gap: 6, marginTop: 2 },
  progressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
    overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: 999, backgroundColor: FlipOn.accent },
  progressLabel: { color: '#A8ADB5', fontSize: 12, fontWeight: '600' },
  heroCta: {
    marginTop: 6,
    minHeight: 46,
    borderRadius: 14,
    backgroundColor: FlipOn.accent,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  heroCtaText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  dismissBtn: {
    minHeight: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: FlipOn.line,
    backgroundColor: FlipOn.surface,
  },
  dismissText: { fontSize: 13, fontWeight: '700', color: FlipOn.ink },

  startCard: {
    backgroundColor: FlipOn.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: FlipOn.line,
    padding: 18,
    gap: 8,
  },
  startIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.accentSoft,
    marginBottom: 2,
  },
  startTitle: { fontSize: 20, fontWeight: '800', color: FlipOn.ink },
  startText: { fontSize: 14, lineHeight: 21, color: FlipOn.muted },
  startCta: {
    marginTop: 8,
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: FlipOn.accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  startCtaText: { color: '#fff', fontSize: 15, fontWeight: '700' },

  section: { gap: 10 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: FlipOn.muted },
  sectionLink: { fontSize: 13, fontWeight: '700', color: FlipOn.accent },
  joinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: FlipOn.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: FlipOn.line,
    padding: 8,
  },
  input: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    paddingHorizontal: 12,
    fontSize: 18,
    fontWeight: '800',
    color: FlipOn.ink,
    letterSpacing: 4,
  },
  joinButton: {
    minHeight: 44,
    minWidth: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.dark,
    paddingHorizontal: 14,
  },
  joinButtonDisabled: { opacity: 0.35 },
  joinButtonText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  joinError: { fontSize: 13, color: FlipOn.danger, fontWeight: '600' },
  hint: { fontSize: 12, lineHeight: 17, color: FlipOn.muted },
  row: {
    backgroundColor: FlipOn.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: FlipOn.line,
    paddingVertical: 14,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rowBody: { flex: 1, gap: 3 },
  rowTitle: { fontSize: 16, fontWeight: '700', color: FlipOn.ink },
  rowMeta: { fontSize: 13, color: FlipOn.muted },
  rowStatus: {
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: 'hidden',
  },
  rowStatusOk: { color: FlipOn.success, backgroundColor: FlipOn.successSoft },
  rowStatusMuted: { color: FlipOn.muted, backgroundColor: FlipOn.soft },

  tipCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: FlipOn.accentSoft,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#FED7AA',
  },
  tipText: { flex: 1, fontSize: 13, lineHeight: 19, color: FlipOn.accentInk, fontWeight: '600' },
});
