import { StyleSheet } from 'react-native';

import { FlipOn, cardShadow } from '@/constants/flipon';

export const homeStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: FlipOn.bg },
  flex: { flex: 1 },
  scroll: { flex: 1 },
  container: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 110,
    gap: 14,
  },
  header: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  hello: {
    fontSize: 15,
    fontWeight: '700',
    color: FlipOn.muted,
    letterSpacing: 0.2,
  },
  cards: { gap: 14 },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: FlipOn.ink,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  pressed: { opacity: 0.88 },

  /* Session active */
  heroWrap: { gap: 0 },
  heroClose: { position: 'absolute', top: 14, right: 14, zIndex: 2 },
  activeCard: {
    minHeight: 168,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: FlipOn.accentBorder,
    backgroundColor: FlipOn.dark,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 18,
    justifyContent: 'space-between',
    ...cardShadow,
  },
  activeBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    minHeight: 96,
  },
  badgeLive: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: FlipOn.accent },
  badgeLiveText: { color: FlipOn.ink, fontSize: 12, fontWeight: '700' },
  activeCode: {
    color: FlipOn.ink,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: 4,
  },
  progressBlock: { width: '72%', marginTop: 4 },
  progressTrack: {
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.12)',
    overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: 999, backgroundColor: FlipOn.accent },
  activeTitle: {
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '800',
    color: FlipOn.ink,
    letterSpacing: -0.2,
  },

  /* Rejoindre */
  joinWrap: { gap: 6 },
  joinInner: { alignItems: 'center', gap: 14, width: '100%' },
  joinInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    maxWidth: 220,
  },
  joinInput: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    paddingHorizontal: 14,
    fontSize: 22,
    fontWeight: '800',
    color: FlipOn.ink,
    letterSpacing: 6,
    textAlign: 'center',
    backgroundColor: FlipOn.soft,
    borderWidth: 1,
    borderColor: FlipOn.line,
  },
  joinGo: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.accent,
  },
  joinGoDisabled: { opacity: 0.35 },
  joinError: {
    fontSize: 13,
    color: FlipOn.danger,
    fontWeight: '600',
    textAlign: 'center',
    paddingHorizontal: 8,
  },

  /* Dernière activité */
  latestBody: { alignItems: 'center', gap: 6, paddingHorizontal: 8 },
  latestName: {
    fontSize: 18,
    fontWeight: '800',
    color: FlipOn.ink,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  latestMeta: { fontSize: 13, color: FlipOn.muted, textAlign: 'center' },
  latestStatus: {
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 2,
  },
  rowStatusOk: { color: FlipOn.success, backgroundColor: FlipOn.successSoft },
  rowStatusMuted: { color: FlipOn.muted, backgroundColor: FlipOn.soft },
});
