import { StyleSheet } from 'react-native';

import { FlipOn, cardShadow } from '@/constants/flipon';
import { platformShadow } from '@/lib/platform-shadow';

/** Styles partagés des écrans de flux — thème sombre premium. */
export const flowStyles = StyleSheet.create({
  loadingCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingTop: 80,
  },
  loadingText: { color: FlipOn.muted, fontSize: 14, fontWeight: '600' },

  progress: { fontSize: 13, fontWeight: '600', color: FlipOn.muted },
  question: { fontSize: 20, fontWeight: '800', color: FlipOn.ink, letterSpacing: -0.4 },

  hero: {
    backgroundColor: FlipOn.dark,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: FlipOn.line,
    padding: 20,
    gap: 8,
    ...cardShadow,
  },
  heroMuted: {
    backgroundColor: FlipOn.soft,
    borderColor: FlipOn.line,
  },
  kicker: {
    color: FlipOn.accent,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  heroTitle: {
    color: FlipOn.ink,
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
    letterSpacing: -0.4,
  },
  heroSubtitle: { color: FlipOn.muted, fontSize: 15, lineHeight: 22 },
  heroMeta: { marginTop: 4, color: FlipOn.muted, fontSize: 13, fontWeight: '600' },

  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  metaPill: {
    color: FlipOn.ink,
    fontSize: 12,
    fontWeight: '700',
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: 'hidden',
  },

  surfaceCard: {
    backgroundColor: FlipOn.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: FlipOn.line,
    padding: 18,
    gap: 10,
    ...cardShadow,
  },
  surfaceTitle: { fontSize: 16, fontWeight: '800', color: FlipOn.ink },
  surfaceLead: { fontSize: 13, lineHeight: 19, color: FlipOn.muted },

  tipCard: {
    backgroundColor: FlipOn.accentSoft,
    borderRadius: 16,
    padding: 14,
    gap: 4,
    borderWidth: 1,
    borderColor: FlipOn.accentBorder,
  },
  tipTitle: { fontSize: 14, fontWeight: '800', color: FlipOn.accentInk },
  tipText: { fontSize: 13, lineHeight: 19, color: FlipOn.accentInk },

  voteCard: {
    backgroundColor: FlipOn.dark,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: FlipOn.line,
    padding: 20,
    gap: 10,
    minHeight: 240,
    ...cardShadow,
  },

  actionsRow: { flexDirection: 'row', gap: 12 },
  passBtn: {
    flex: 1,
    minHeight: 54,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: FlipOn.line,
    backgroundColor: FlipOn.soft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  passText: { fontSize: 16, fontWeight: '700', color: FlipOn.ink },
  yesBtn: {
    flex: 1,
    minHeight: 54,
    borderRadius: 14,
    backgroundColor: FlipOn.accent,
    alignItems: 'center',
    justifyContent: 'center',
    ...platformShadow({
      color: FlipOn.accent,
      offset: { width: 0, height: 6 },
      opacity: 0.35,
      radius: 12,
      elevation: 4,
    }),
  },
  yesText: { fontSize: 16, fontWeight: '700', color: FlipOn.onAccent },
  disabled: { opacity: 0.5 },

  hint: { fontSize: 12, color: FlipOn.muted, lineHeight: 18, textAlign: 'center' },

  primaryButton: {
    minHeight: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.accent,
    ...platformShadow({
      color: FlipOn.accent,
      offset: { width: 0, height: 6 },
      opacity: 0.3,
      radius: 12,
      elevation: 4,
    }),
  },
  primaryText: { color: FlipOn.onAccent, fontSize: 15, fontWeight: '700' },
  secondaryButton: {
    minHeight: 50,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.soft,
    borderWidth: 1,
    borderColor: FlipOn.line,
  },
  secondaryText: { color: FlipOn.ink, fontSize: 15, fontWeight: '700' },
  ghostButton: {
    minHeight: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: FlipOn.line,
    backgroundColor: FlipOn.bg,
  },
  ghostText: { color: FlipOn.ink, fontSize: 14, fontWeight: '700' },
  dangerButton: {
    minHeight: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: FlipOn.dangerLine,
    backgroundColor: FlipOn.dangerSoft,
  },
  dangerText: { color: FlipOn.danger, fontSize: 14, fontWeight: '700' },

  joinHero: {
    alignItems: 'center',
    gap: 14,
    backgroundColor: FlipOn.dark,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: FlipOn.line,
    paddingVertical: 32,
    paddingHorizontal: 24,
    marginTop: 24,
    ...cardShadow,
  },
  joinCode: {
    fontSize: 28,
    fontWeight: '800',
    color: FlipOn.ink,
    letterSpacing: 3,
  },
  joinTitle: { fontSize: 20, fontWeight: '800', color: FlipOn.ink, textAlign: 'center' },
  joinText: { color: FlipOn.muted, fontSize: 14, textAlign: 'center', lineHeight: 21 },

  phaseLabel: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: FlipOn.accent,
  },
  roadmapRow: { flexDirection: 'row', gap: 12, minHeight: 56 },
  timeline: { width: 16, alignItems: 'center' },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: FlipOn.accent,
    marginTop: 4,
  },
  timelineLine: {
    flex: 1,
    width: 2,
    backgroundColor: FlipOn.line,
    marginTop: 4,
    marginBottom: 2,
  },
  roadmapBody: { flex: 1, gap: 4, paddingBottom: 12 },
  roadmapHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  roadmapTitle: { flex: 1, fontSize: 15, fontWeight: '700', color: FlipOn.ink },
  roadmapMinutes: { fontSize: 12, fontWeight: '700', color: FlipOn.muted },
  roadmapDetail: { fontSize: 14, lineHeight: 20, color: FlipOn.muted },
  phaseBlock: { gap: 10 },

  teaserCta: {
    marginTop: 6,
    alignSelf: 'flex-start',
    minHeight: 42,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: FlipOn.accent,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.accentSoft,
  },
  teaserCtaText: { fontSize: 14, fontWeight: '700', color: FlipOn.accentInk },
});
