import { StyleSheet } from 'react-native';

import { FlipOn } from '@/constants/flipon';

export const authStyles = StyleSheet.create({
  card: {
    backgroundColor: FlipOn.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: FlipOn.line,
    padding: 16,
    gap: 10,
  },
  /** Sans bordure : le parent (`login` formBlock) fournit déjà le cadre. */
  cardFlush: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
  },
  cardTitle: { fontSize: 15, fontWeight: '700', color: FlipOn.ink },
  screenTitle: { fontSize: 18, fontWeight: '800', color: FlipOn.ink, marginBottom: 2 },
  hint: { fontSize: 12, lineHeight: 18, color: FlipOn.muted },
  error: { fontSize: 13, color: FlipOn.danger, lineHeight: 18 },
  input: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: FlipOn.line,
    paddingHorizontal: 14,
    fontSize: 15,
    color: FlipOn.ink,
    backgroundColor: FlipOn.surface,
  },
  identityHit: {
    flexDirection: 'row',
    gap: 14,
    alignItems: 'center',
    paddingVertical: 2,
  },
  pressed: { opacity: 0.72 },
  avatar: {
    height: 56,
    width: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.accentSoft,
  },
  avatarText: { fontSize: 18, fontWeight: '800', color: FlipOn.accentInk },
  headerText: { flex: 1, gap: 3, minWidth: 0 },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  name: { fontSize: 20, fontWeight: '800', color: FlipOn.ink, flexShrink: 1 },
  planPill: {
    backgroundColor: FlipOn.accentSoft,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  planPillText: { fontSize: 11, fontWeight: '800', color: FlipOn.accentInk },
  email: { fontSize: 13, color: FlipOn.muted },
  editHint: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '600',
    color: FlipOn.accentInk,
  },
  primaryButton: {
    minHeight: 50,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: FlipOn.accent,
  },
  primaryText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  secondaryButton: {
    minHeight: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: FlipOn.line,
    backgroundColor: FlipOn.surface,
  },
  secondaryText: { fontSize: 14, fontWeight: '700', color: FlipOn.ink },
  dividerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 2 },
  divider: { flex: 1, height: 1, backgroundColor: FlipOn.line },
  dividerText: { fontSize: 12, color: FlipOn.muted, fontWeight: '600' },
  link: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '600',
    color: FlipOn.accentInk,
    textAlign: 'center',
  },
});
